Nova rota allMeanings
ThiagoNelsi/dicio-api pull request #20
Opened 2021-11-13 16:52 UTC by FernandoGuiao

E ae Thiago!

Construí uma nova rota para mostrar os significados da palavra inserida com todas as formas de acentuações, de acordo com o disponível no dicio.com.br.
Como seria diferente da utilidade da rota '/meanings', retornaria significados de palavras diferentes, e é uma requisição mais lenta, devido às várias requisições ao site do dicio.com.br, achei melhor deixar em rota separada.

Ainda não resolve completamente a Issue #19, mas achei uma funcionalidade interessante.

2021-11-17 05:21 UTC, ThiagoNelsi requested changes
**Valeu pelo PR!!** Apesar da lentidão dessa solução, foi uma boa abordagem para resolver o problema. Futuramente podemos encontrar uma forma de resolver isso.

Fiz algumas observações para serem corrigidas antes de fazer o merge do PR.

Valeu novamente!!!

2021-11-17 05:21 UTC, ThiagoNelsi commented on README.md
> +    title: String,
O que acha de colocar `word` ao invés de `title`? Me parece mais intuitivo

2021-11-17 05:21 UTC, ThiagoNelsi commented on src/allMeanings.js
> +        noError = false;
Em caso de utilizar o `while (true) { ... }` substituir por um `break`

2021-11-17 05:21 UTC, ThiagoNelsi commented on src/allMeanings.js
> +    while (noError) {
Para evitar criar variáveis desnecessárias podemos utilizar um `while (true) { ... }` e parar o loop com o `break` em caso de erro.

2021-11-17 05:41 UTC, ThiagoNelsi requested changes

2021-11-17 05:41 UTC, ThiagoNelsi commented on src/allMeanings.js
> +        if (followUrl +"/" != $("[rel$='canonical']").attr("href") && i > 1) {
A leitura dessa condicional é mais difícil, abstraia em uma função com um nome que descreva seu intuito e adicione um comentário explicando.

Exemplo:
```js

...

if (isRedirectUrl()) { ... }

...

// This function verifies if...
function isRedirectUrl() { ... }
```

2021-11-17 21:51 UTC, FernandoGuiao commented
Fiz as alterações. Concordo em todos os pontos do review.
Se eu tiver entendido mal algum ponto, pode mandar outro review que resolvo aqui tb.
Valeu!

2021-11-18 01:59 UTC, ThiagoNelsi commented
Show! Valeu pela contribuição!!

2021-11-18 02:02 UTC, merged